[package]
name = "sorrel-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", optional = true }
monostate = "1.0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = { version = "3.16.1", features = ["hex"] }
uuid = { version = "1.20.0", features = ["serde", "v4"] }

[features]
axum = ["dep:axum"]
